### ISSUE TITLE
Build status

### ISSUE THREAD

**Issue by togo59** [JuliaDB/DBAPI.jl#15]
https://github.com/JuliaDB/DBAPI.jl shows Builds Failing
whereas
https://pkg.julialang.org/detail/DBAPI.html  shows: Julia v0.6: 0.1.0 (a month ago) / Tests pass.
Which is it?

**Comment by rofinn** [comment]
@togo59 The travis build currently doesn't allow failures on julia nightly which is why it's showing up as failed. The julia 0.6 tests are still passing as of 3 days ago.

**Comment by togo59** [comment]
Thx!
