### ISSUE TITLE
In METADATA? 

### ISSUE THREAD

**Issue by aviks** [JuliaDB/DBAPI.jl#3]
Can we put this package in METADATA? We've been trying use this API in JDBC.jl. I think this is stable enough to implement now...

cc: @ViralBShah

**Comment by ViralBShah** [comment]
+1

**Comment by iamed2** [comment]
It is already in METADATA. 

Speaking of stability, I've done some changes to query types that remove the need for a separate `executemany!` method and make implementing that flow easier for drivers. I guess it's time to test, push, and tag that!

**Comment by ViralBShah** [comment]
That is indeed right! Would be nice to tag a new version, as we start using it across various databases.

**Comment by iamed2** [comment]
I'm on it! It'll be out today.

**Comment by iamed2** [comment]
New version tagged and PR open on METADATA.

Next releases will be:
- Generated docs from the docstrings, and maybe a guide
- Result set objects, if I find them to be very important for implementing async protocols (currently working through that with PostgreSQL)

**Comment by iamed2** [comment]
In general I won't make any guarantees of stability until I hit `0.1.0`, but this should be mostly consistent for now.

**Comment by iamed2** [comment]
0.0.2 is now in METADATA
