### ISSUE TITLE
Tests fail on v0.5

### ISSUE THREAD

**Issue by ranjanan** [JuliaDB/DBAPI.jl#9]
The tests in the Arrays category fail with the following error trace for each failed fact:

```
ERROR: MethodError: no method matching length(::DBAPI.ArrayInterfaces.ColumnarArrayRowIterator) # Could be ColumnIterator too
Closest candidates are:
  length(::SimpleVector) at essentials.jl:168
  length(::Base.MethodList) at reflection.jl:256
  length(::MethodTable) at reflection.jl:322
  ...
 in _similar_for at ./array.jl:262 [inlined]
 in _collect at ./array.jl:277 [inlined]
 in collect(::DBAPI.ArrayInterfaces.ColumnarArrayRowIterator) at ./array.jl:273
```

This isn't in an issue on v0.4, and tests pass there. 

I checked the various methods defined for `length` and I found this one method that got defined in v0.4 but _not_ in v0.5

```
length(cursor::DBAPI.ArrayInterfaces.ColumnarArrayCursor) at /Users/ranjan/.julia/v0.4/DBAPI/src/arrays.jl:107
```

I wonder if this is causing the issue.

**Comment by ranjanan** [comment]
cc: @mdpradeep

**Comment by iamed2** [comment]
Tracked it down; looks like `collect` requires `length` on 0.5 but not on 0.4. Might have something to do with some traits?
